name: 'Tests'

on:
  push:
  pull_request:

jobs:
  test-80-zts:
    container: malusevd99/php-ext-dev:8.0-zts
    name: Tests (PHP 8.0 ZTS)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PHP UV with LibUV submodule'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Compiling LibUV'
        working-directory: 'third-party/libuv'
        run: |
          ./autogen.sh
          ./configure --prefix=$(readlink -f `pwd`/../../libuv)
          make -j8
          make install
      - name: 'Compiling PHP UV extension'
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make -j8
          sudo make install
          echo "extension = uv.so" >> $(php -r 'echo php_ini_loaded_file();')
      # - name: 'Running Tests'
      #   run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
  test-80:
    container: malusevd99/php-ext-dev:8.0
    name: Tests (PHP 8.0)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PHP UV with LibUV submodule'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Compiling LibUV'
        working-directory: 'third-party/libuv'
        run: |
          ./autogen.sh
          ./configure --prefix=$(readlink -f `pwd`/../../libuv)
          make -j8
          make install
      - name: 'Compiling PHP UV extension'
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make -j8
          sudo make install
          echo "extension = uv.so" >> $(php -r 'echo php_ini_loaded_file();')
      # - name: 'Running Tests'
      #   run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
  test-81:
    container: malusevd99/php-ext-dev:8.1
    name: Tests (PHP 8.1)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PHP UV with LibUV submodule'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Compiling LibUV'
        working-directory: 'third-party/libuv'
        run: |
          ./autogen.sh
          ./configure --prefix=$(readlink -f `pwd`/../../libuv)
          make -j8
          make install
      - name: 'Compiling PHP UV extension'
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make -j8
          sudo make install
          echo "extension = uv.so" >> $(php -r 'echo php_ini_loaded_file();')
      # - name: 'Running Tests'
      #   run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
  test-81-zts:
    container: malusevd99/php-ext-dev:8.1-zts
    name: Tests (PHP 8.1 ZTS)
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout PHP UV with LibUV submodule'
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: 'Compiling LibUV'
        working-directory: 'third-party/libuv'
        run: |
          ./autogen.sh
          ./configure --prefix=$(readlink -f `pwd`/../../libuv)
          make -j8
          make install
      - name: 'Compiling PHP UV extension'
        run: |
          phpize
          ./configure --with-uv=$(readlink -f `pwd`/libuv)
          make -j8
          sudo make install
          echo "extension = uv.so" >> $(php -r 'echo php_ini_loaded_file();')
      # - name: 'Running Tests'
      #   run: php run-tests.php -p `which php` --offline --show-diff --set-timeout 120
